services:
  web:
    build: .
    image: meusite:lastest
    container_name: meu-site
    ports:
      - 80:80
      - 443:443
    networks:
      - meusite
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks: 
  meusite:
    name: meusite
    